# Generated by Django 6.0.4 on 2026-04-19 15:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Node",
            fields=[
                ("path", models.CharField(max_length=255, unique=True)),
                ("depth", models.PositiveIntegerField()),
                ("numchild", models.PositiveIntegerField(default=0)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "node_type",
                    models.CharField(
                        choices=[
                            ("discussion", "Discussion"),
                            ("post", "Post"),
                            ("link", "Link"),
                        ],
                        default="discussion",
                        max_length=20,
                    ),
                ),
                ("sequence_index", models.IntegerField(default=0)),
                (
                    "permission_mode",
                    models.CharField(
                        choices=[("inherited", "Inherited"), ("custom", "Custom")],
                        default="inherited",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("label", models.CharField(blank=True, max_length=255)),
                (
                    "resolution_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("accept", "Accept"),
                            ("reject", "Reject"),
                            ("close", "Close"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("child_count", models.PositiveIntegerField(default=0)),
                ("content", models.TextField(blank=True)),
                ("reopens_discussion", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "nodes",
            },
        ),
        migrations.CreateModel(
            name="PostRevision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "post_revisions",
                "ordering": ["-created_at"],
            },
        ),
    ]
