# Generated by Django 6.0.4 on 2026-04-20 07:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nodes", "0002_initial"),
        ("spaces", "0003_spaceinvite"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="node",
            index=models.Index(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=["deleted_at"],
                name="nodes_deleted_at_partial",
            ),
        ),
    ]
