# Generated by Django 6.0.4 on 2026-04-21 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nodes", "0003_add_deleted_at_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="node",
            name="is_draft",
            field=models.BooleanField(default=False),
        ),
    ]