# Generated by Django 6.0.4 on 2026-04-21 17:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nodes", "0004_node_is_draft"),
        ("spaces", "0005_role_can_view_drafts"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="node",
            options={"verbose_name": "node", "verbose_name_plural": "nodes"},
        ),
        migrations.AlterModelOptions(
            name="postrevision",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "post revision",
                "verbose_name_plural": "post revisions",
            },
        ),
        migrations.AddIndex(
            model_name="node",
            index=models.Index(fields=["node_type"], name="nodes_node_type_idx"),
        ),
        migrations.AddIndex(
            model_name="node",
            index=models.Index(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=["space", "node_type"],
                name="nodes_space_node_type_idx",
            ),
        ),
    ]
