# Generated by Django 6.0.4 on 2026-04-23 00:00

import apps.invitations.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("spaces", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SpaceInvite",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("accepted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("rejected_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ("email", models.EmailField(blank=True, db_index=True, default="", max_length=254)),
                ("expires_at", models.DateTimeField(db_index=True, default=apps.invitations.models.default_invite_expiry)),
                ("last_sent_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                (
                    "accepted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_accepted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rejected_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_rejected",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="invites", to="spaces.role"),
                ),
                (
                    "space",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="invites", to="spaces.space"),
                ),
            ],
            options={
                "verbose_name": "space invite",
                "verbose_name_plural": "space invites",
                "db_table": "space_invites",
            },
        ),
    ]
