# Generated by Django 6.0.4 on 2026-04-23 04:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Reaction",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reaction_type",
                    models.CharField(
                        choices=[("like", "Like"), ("dislike", "Dislike")],
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "reaction",
                "verbose_name_plural": "reactions",
                "db_table": "reactions",
            },
        ),
    ]
