# Generated by Django 6.0.4 on 2026-04-19 15:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("nodes", "0001_initial"),
        ("spaces", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to="nodes.node",
                    ),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to="spaces.spaceparticipant",
                    ),
                ),
            ],
            options={
                "db_table": "subscriptions",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("participant", "node"),
                        name="subscriptions_participant_node_unique",
                    )
                ],
            },
        ),
    ]
