# Generated by Django 6.0.4 on 2026-04-22 15:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("post_created", "Post created"),
                            ("discussion_resolved", "Discussion resolved"),
                            ("discussion_reopened", "Discussion reopened"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "resolution_type",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("read_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "notification",
                "verbose_name_plural": "notifications",
                "db_table": "notifications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
            options={
                "verbose_name": "subscription",
                "verbose_name_plural": "subscriptions",
                "db_table": "subscriptions",
            },
        ),
    ]
