# Generated by Django 6.0.4 on 2026-04-23 04:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Opinion",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "opinion_type",
                    models.CharField(
                        choices=[
                            ("agree", "Agree"),
                            ("abstain", "Abstain"),
                            ("disagree", "Disagree"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "opinion",
                "verbose_name_plural": "opinions",
                "db_table": "opinions",
            },
        ),
    ]
