# Generated by Django 6.0.4 on 2026-04-19 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("nodes", "0001_initial"),
        ("opinions", "0001_initial"),
        ("spaces", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="opinion",
            name="participant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="opinions",
                to="spaces.spaceparticipant",
            ),
        ),
        migrations.AddField(
            model_name="reaction",
            name="participant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reactions",
                to="spaces.spaceparticipant",
            ),
        ),
        migrations.AddField(
            model_name="reaction",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reactions",
                to="nodes.node",
            ),
        ),
        migrations.AddConstraint(
            model_name="opinion",
            constraint=models.UniqueConstraint(
                fields=("participant", "node"), name="opinions_participant_node_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="reaction",
            constraint=models.UniqueConstraint(
                fields=("participant", "post"), name="reactions_participant_post_unique"
            ),
        ),
    ]
