# Generated by Django 6.0.4 on 2026-04-23 04:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("discussions", "0002_initial"),
        ("opinions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="opinion",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="opinion",
            name="discussion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="opinions",
                to="discussions.discussion",
            ),
        ),
        migrations.AddConstraint(
            model_name="opinion",
            constraint=models.UniqueConstraint(
                fields=("created_by", "discussion"),
                name="opinions_user_discussion_unique",
            ),
        ),
    ]
