# Generated by Django 6.0.4 on 2026-04-21 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("opinions", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="opinion",
            options={"verbose_name": "opinion", "verbose_name_plural": "opinions"},
        ),
        migrations.AlterModelOptions(
            name="reaction",
            options={"verbose_name": "reaction", "verbose_name_plural": "reactions"},
        ),
    ]
