# Generated by Django 6.0.4 on 2026-04-22 15:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Discussion",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("sequence_index", models.PositiveIntegerField(default=0)),
                (
                    "resolution_type",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("path", models.CharField(max_length=255, unique=True)),
                ("depth", models.PositiveIntegerField()),
                ("numchild", models.PositiveIntegerField(default=0)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("label", models.CharField(blank=True, default="", max_length=255)),
            ],
            options={
                "verbose_name": "discussion",
                "verbose_name_plural": "discussions",
                "db_table": "discussions",
                "ordering": ["path"],
            },
        ),
    ]
