# Generated by Django 6.0.4 on 2026-04-23 04:03

import apps.spaces.models
import django.contrib.postgres.fields
import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("label", models.CharField(max_length=100)),
                (
                    "post_highlight_color",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid hex color like #A1B2C3.",
                                regex="^#[0-9A-Fa-f]{6}$",
                            )
                        ],
                    ),
                ),
                ("can_post", models.BooleanField(default=True)),
                ("can_create_draft", models.BooleanField(default=True)),
                ("can_edit_others_post", models.BooleanField(default=False)),
                ("can_delete_own_post", models.BooleanField(default=True)),
                ("can_view_history", models.BooleanField(default=True)),
                ("can_create_discussion", models.BooleanField(default=False)),
                ("can_rename_discussion", models.BooleanField(default=False)),
                ("can_delete_discussion", models.BooleanField(default=False)),
                ("can_promote_post", models.BooleanField(default=False)),
                ("can_set_permissions", models.BooleanField(default=False)),
                ("can_resolve", models.BooleanField(default=False)),
                ("can_reopen_discussion", models.BooleanField(default=False)),
                ("can_reorganise", models.BooleanField(default=False)),
                ("can_restructure", models.BooleanField(default=False)),
                ("can_moderate_content", models.BooleanField(default=False)),
                ("can_manage_participants", models.BooleanField(default=False)),
                ("can_close_space", models.BooleanField(default=False)),
                ("can_archive_space", models.BooleanField(default=False)),
                ("can_unarchive_space", models.BooleanField(default=False)),
                ("can_modify_closed_space", models.BooleanField(default=False)),
                ("can_view_drafts", models.BooleanField(default=False)),
                ("can_opine", models.BooleanField(default=True)),
                ("can_react", models.BooleanField(default=True)),
                ("is_default", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "role",
                "verbose_name_plural": "roles",
                "db_table": "roles",
            },
        ),
        migrations.CreateModel(
            name="Space",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("information", models.TextField(blank=True, default="")),
                (
                    "lifecycle",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("open", "Open"),
                            ("closed", "Closed"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("starts_at", models.DateTimeField(blank=True, null=True)),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                (
                    "is_public",
                    models.BooleanField(
                        default=True,
                        help_text="Public spaces are listed and can be joined directly. Private spaces require invites.",
                    ),
                ),
                (
                    "opinion_types",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=20),
                        blank=True,
                        default=list,
                        help_text='Subset of ["agree", "abstain", "disagree"]',
                        validators=[apps.spaces.models.validate_opinion_types],
                    ),
                ),
                (
                    "reaction_types",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=20),
                        blank=True,
                        default=list,
                        help_text='Subset of ["like", "dislike"]',
                        validators=[apps.spaces.models.validate_reaction_types],
                    ),
                ),
                (
                    "edit_window_minutes",
                    models.PositiveIntegerField(
                        blank=True,
                        default=None,
                        help_text="Minutes after posting during which edits are allowed. None = no limit, 0 = disabled.",
                        null=True,
                    ),
                ),
                (
                    "template_slug",
                    models.CharField(blank=True, default="", max_length=100),
                ),
            ],
            options={
                "verbose_name": "space",
                "verbose_name_plural": "spaces",
                "db_table": "spaces",
                "ordering": ["-updated_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SpaceInvite",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        db_index=True, default=apps.spaces.models.default_invite_expiry
                    ),
                ),
            ],
            options={
                "verbose_name": "space invite",
                "verbose_name_plural": "space invites",
                "db_table": "space_invites",
            },
        ),
        migrations.CreateModel(
            name="SpaceParticipant",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
            options={
                "verbose_name": "space participant",
                "verbose_name_plural": "space participants",
                "db_table": "space_participants",
            },
        ),
    ]
