# Generated by Django 6.0.4 on 2026-04-19 15:57

import apps.spaces.models
import django.contrib.postgres.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("label", models.CharField(max_length=100)),
                ("can_post", models.BooleanField(default=True)),
                ("can_shape_tree", models.BooleanField(default=False)),
                ("can_set_permissions", models.BooleanField(default=False)),
                ("can_resolve", models.BooleanField(default=False)),
                ("can_reorganise", models.BooleanField(default=False)),
                ("can_moderate", models.BooleanField(default=False)),
                ("can_close_space", models.BooleanField(default=False)),
                ("can_opine", models.BooleanField(default=True)),
                ("can_react", models.BooleanField(default=True)),
                ("is_default", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "roles",
            },
        ),
        migrations.CreateModel(
            name="Space",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "lifecycle",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("open", "Open"),
                            ("closed", "Closed"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("starts_at", models.DateTimeField(blank=True, null=True)),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                (
                    "opinion_types",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=20),
                        blank=True,
                        default=list,
                        help_text='Subset of ["agree", "abstain", "disagree"]',
                        validators=[apps.spaces.models.validate_opinion_types],
                    ),
                ),
                (
                    "reaction_types",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=20),
                        blank=True,
                        default=list,
                        help_text='Subset of ["like", "dislike"]',
                        validators=[apps.spaces.models.validate_reaction_types],
                    ),
                ),
                (
                    "edit_window_minutes",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Minutes after posting during which edits are allowed. 0 = editing disabled.",
                    ),
                ),
                ("template_slug", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "spaces",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SpaceParticipant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "space_participants",
            },
        ),
    ]
