# Generated by Django 6.0.4 on 2026-04-19 15:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("nodes", "0002_initial"),
        ("spaces", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="space",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_spaces",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="space",
            name="default_role",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="default_for_spaces",
                to="spaces.role",
            ),
        ),
        migrations.AddField(
            model_name="space",
            name="root_discussion",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="root_of_space",
                to="nodes.node",
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="space",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="roles",
                to="spaces.space",
            ),
        ),
        migrations.AddField(
            model_name="spaceparticipant",
            name="role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="participants",
                to="spaces.role",
            ),
        ),
        migrations.AddField(
            model_name="spaceparticipant",
            name="space",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="participants",
                to="spaces.space",
            ),
        ),
        migrations.AddField(
            model_name="spaceparticipant",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="participations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="role",
            constraint=models.UniqueConstraint(
                fields=("space", "label"), name="roles_space_label_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="spaceparticipant",
            constraint=models.UniqueConstraint(
                fields=("space", "user"), name="space_participants_space_user_unique"
            ),
        ),
    ]
