# Generated by Django 6.0.4 on 2026-04-21 00:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spaces", "0003_spaceinvite"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="space",
            options={"db_table": "spaces", "ordering": ["-updated_at", "-created_at"]},
        ),
        migrations.AddField(
            model_name="space",
            name="information",
            field=models.TextField(blank=True, default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="space",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="space",
            name="edit_window_minutes",
            field=models.PositiveIntegerField(
                blank=True,
                default=None,
                help_text="Minutes after posting during which edits are allowed. None = no limit, 0 = disabled.",
                null=True,
            ),
        ),
    ]