# Generated by Django 6.0.4 on 2026-04-21 00:00

from django.db import migrations, models


def set_facilitator_draft_visibility(apps, schema_editor):
    Role = apps.get_model("spaces", "Role")
    Role.objects.filter(label="Facilitator").update(can_view_drafts=True)


def unset_facilitator_draft_visibility(apps, schema_editor):
    Role = apps.get_model("spaces", "Role")
    Role.objects.filter(label="Facilitator").update(can_view_drafts=False)


class Migration(migrations.Migration):

    dependencies = [
        ("spaces", "0004_space_information_updated_at_edit_window_nullable"),
    ]

    operations = [
        migrations.AddField(
            model_name="role",
            name="can_view_drafts",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(set_facilitator_draft_visibility, unset_facilitator_draft_visibility),
    ]