# Generated by Django 6.0.4 on 2026-04-21 17:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nodes", "0005_alter_node_options_alter_postrevision_options_and_more"),
        ("spaces", "0005_role_can_view_drafts"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="role",
            options={"verbose_name": "role", "verbose_name_plural": "roles"},
        ),
        migrations.AlterModelOptions(
            name="space",
            options={
                "ordering": ["-updated_at", "-created_at"],
                "verbose_name": "space",
                "verbose_name_plural": "spaces",
            },
        ),
        migrations.AlterModelOptions(
            name="spaceinvite",
            options={
                "verbose_name": "space invite",
                "verbose_name_plural": "space invites",
            },
        ),
        migrations.AlterModelOptions(
            name="spaceparticipant",
            options={
                "verbose_name": "space participant",
                "verbose_name_plural": "space participants",
            },
        ),
        migrations.AddIndex(
            model_name="space",
            index=models.Index(fields=["lifecycle"], name="spaces_lifecycle_idx"),
        ),
    ]
